server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    # para evitar autoregistro - util se exists varios eurekas
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
spring:
  application:
    name: naming-server
  management:
    tracing:
      sampling:
        probability: 1.0
  zipkin:
    base-url: ${SPRING_ZIPKIN_BASEURL:http://localhost:9411}
